### ISSUE TITLE
[question] use external postgres server in production

### ISSUE THREAD

**Issue by ygol** [Tecnativa/doodba-copier-template#113]
Hello,

Where/how may I configure the use of an external database but only for production?
thank you

**Comment by Yajo** [comment]
Just use this option. Then, later, configure the `prod.yaml` environment according to your needs:
https://github.com/Tecnativa/doodba-copier-template/blob/dbaecbd1c60c86531e3b1ba0941dc85ef6ab79a4/copier.yml#L291

**Comment by ygol** [comment]
Tnx for feedback Yajo but using this option generate errors:

* in `invoke img-pull`: 
`Pulling db                     ... error`

* in `invoke resetdb` and `invoke start`: 
```
ERROR: manifest for tecnativa/postgres-autoconf:None-alpine not found: manifest unknown: manifest unknown
Pulling db (tecnativa/postgres-autoconf:None-alpine)...
ERROR: manifest for tecnativa/postgres-autoconf:None-alpine not found: manifest unknown: manifest unknown
```

**Comment by ska-ibees** [comment]
I am facing the same issue after #150 
Can we have 'DATABASE_URL' in copier question to get some flexibility? Like I intend to deploy Doodba on AWS EC2 by connecting it to AWS RDS database (Over network).

**Comment by joao-p-marques** [comment]
This bug has been fixed in https://github.com/Tecnativa/doodba-copier-template/pull/150, and later in https://github.com/Tecnativa/doodba-copier-template/pull/159

**Comment by bosd** [comment]
@ygol How did you setup the communication with an external postgres server?
Is it also possible in devel environment?
