### ISSUE TITLE
[Question] How to do scaffold a module with doodba

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#134]
Hello 

How is the correct way to scaffold a module with doodba with copier?

Odoo scaffold is: 

./odoo-bin scaffold your_module_name addons/

¿How can I achieve this?

Thank you

**Comment by Yajo** [comment]
No idea, I never did that, and I doubt it's supported due to filesystem permissions.

I guess the best would be to have a copier template for odoo modules, something I've been missing for a long time. But that would be better as an OCA repo probably.

Closing, as this is not really an issue.
