### ISSUE TITLE
IDEA - Restore in Test / Dev

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba-copier-template#136]
Hi,

The basic idea is this from a layman's standpoint.

Take the current duplicity container but have no scheduled backups or backup capability. The only thing it can do is restore.

Then in dev and test if we need current client data, and we have the correct decrypt keys/credentials can simply issue a recover command or similar, and the relevant psql command and then be in sync with latest production or earlier if desired.

As an aside, in order to use swift containers `swift://` you need the S3 version however the copier templates don't specify it

**Comment by Yajo** [comment]
It shouldn't be a problem:

```bash
# 1) restore data using the backup container from prod.yaml
docker-compose -f prod.yaml run --rm backup sh -c 'restore && (dropdb --if-exists $PGDATABASE; createdb; psql -f $SRC/prod.sql)'`
# 2) destroy the prod environment, except volumes
docker-compose -f prod.yaml down
# 3) boot another environment, like test.yaml
docker-compose -f test.yaml up -d
```

**Comment by gdgellatly** [comment]
@Yajo yes, except for the small chance of a backup cron kicking off in the middle of it.

**Comment by Yajo** [comment]
> or I suppose run doesn't have crons run

Correct.
