### ISSUE TITLE
Error command copier copy

### ISSUE THREAD

**Issue by ValentinVinagre** [Tecnativa/doodba-copier-template#14]
Hi @Yajo ,
When I launch the command copier copy gh:Tecnativa/doodba-copier-template ~/path the system return one error, I don't know if is configuration or the template.
Error:
<img width="1173" alt="Captura de pantalla 2020-03-25 a las 14 47 28" src="https://user-images.githubusercontent.com/22913794/77543194-9cf33600-6ea7-11ea-8bf2-123551096c05.png">

Thanks,

**Comment by Yajo** [comment]
Please paste the full log.

**Comment by ValentinVinagre** [comment]
Hi @Yajo ,
I have uploaded the full log.

**Comment by Yajo** [comment]
It seems to be a bug in copier itself.

Try this:

```
copier copy https://github.com/Tecnativa/doodba-copier-template.git destination
```

I'll try to fix in  copier ASAP.

**Comment by ValentinVinagre** [comment]
Hi @Yajo ,
works fine 👍 , but in some questions it's a little bit difficult (example: emails smtp is confusing).
If we need to use/add the EE, the 'wizard' doesn't have the option to set the ssh access to connect to github (a little improvement?)

Thanks for all,

**Comment by Yajo** [comment]
> in some questions it's a little bit difficult

Yes I know. In Copier itself there's https://github.com/pykong/copier/issues/161 which should allow us to ask things such as "do you want to configure smtp?" and skip all the :meat_on_bone: if you don't want to.

**Comment by ValentinVinagre** [comment]
The option would be great, to be version 1.01 the truth is that it is a great job 😄

**Comment by Yajo** [comment]
Thanks!

Maybe you want to open another issue for https://github.com/Tecnativa/doodba-copier-template/issues/14#issuecomment-603915940.

For now, this will be fixed once https://github.com/pykong/copier/issues/168 is fixed.
