### ISSUE TITLE
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here   in "./prod.yaml", line 28, column 41

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#143]
I tried a fresh copier execution:

copier -a copier-answers.yml .

and when i try to build the image with: 

docker-compose -f prod.yaml up --build --remove-orphans --force-recreate -d

I got this error:

ERROR: yaml.scanner.ScannerError: mapping values are not allowed here   in "./prod.yaml", line 28, column 41
Line 28:

      traefik.main-0.frontend.rule: Host:

The answers file:

# Changes here will be overwritten by Copier
_commit: v2.3.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_tz: UTC
cidr_whitelist: null
domains_prod:
- servicios.racomx.com
domains_test:
- testservicios.racomx.com
gitlab_url: null
odoo_dbfilter: ^%d$
odoo_initial_lang: es_MX
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 13.0
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: servicios
postgres_username: ffffffff
postgres_version: 12
project_author: Real Systems
project_license: AGPL-3.0-or-later
project_name: proj2021
smtp_canonical_default: racomx.com
smtp_canonical_domains:
- realsystems.com.mx
smtp_default_from: x@x.com
smtp_relay_host: smtp.server.mx
smtp_relay_port: 587
smtp_relay_user: x@x.com

**Comment by joao-p-marques** [comment]
Hi. This is happening because the copier answers mechanism has changed, and you now need to provide the `prod` and `test` domains through a YAML array, like this:
```yaml
# ...

domains_prod? Format: yaml
🎤 [None]: - hosts: [servicios.racomx.com]

# ...

domains_test? Format: yaml
🎤 [None]: - hosts: [testservicios.racomx.com]

# ...
```

There is an example in the copier question, so use that as a reference.

**Comment by carlosecv** [comment]
Yes this was the error

The syntax of prod and test domains has changed a lot 

Thank you
