### ISSUE TITLE
ERROR: Invalid interpolation format for "environment" option in service "odoo": "^%d$"

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#146]
Previous version of copier I can put ^%d$ as dbfilter on copier Questions now I receive this ERROR

ERROR: Invalid interpolation format for "environment" option in service "odoo": "^%d$"

when i try:

docker-compose -f prod.yaml build --no-cache ; docker-compose -f prod.yaml up --build --remove-orphans --force-recreate -d

**Comment by theangryangel** [comment]
Try a double $, which should escape it.

**Comment by Yajo** [comment]
Yes, check out this: https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution

**Comment by carlosecv** [comment]
Thank you it worked
