### ISSUE TITLE
Pinned Doodba Version incompatible with copier update

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba-copier-template#147]
Not sure what you can do to be honest, maybe versioning of some kind for copier, but changing env vars and vscode configs while not respecting a pinned version using prior values is going to cause problems. But best to know I suppose

**Comment by Yajo** [comment]
I don't understand you, could you be more specific?

**Comment by gdgellatly** [comment]
We had a case where we had to pin a v11 config because the underlying build changed underlying OS and would no longer build due to exotic dependencies.

Then we ran copier update, which changed the env vars - specifically in relation to PTVSD and DEBUGPY while removing the .env file. The debug configs for VSCode also changed, but the old pinned version did not have the new dependencies.

As I say not much you can do, its fine, we worked it out.

**Comment by Yajo** [comment]
OK, well... in case you keep the same `odoo_version` for the template when updating, if you changed later manually the line produced by this one, the smart update diff should leave the same one you had: https://github.com/Tecnativa/doodba-copier-template/blob/4b85e88858b2e56aa1be25adacdd5d9953897198/odoo/Dockerfile#L2

In case you're updating the `odoo_version` (from 11 to 12 for example), then a conflict should happen and you should have a `Dockerfile.rej` file there, which you should review manually, just like you would do with any other git conflict.

Pinning is something that's not on our rodamap for the template, apart from the fact that you can rely on copier's smart update diff as said. I think we can safely close this one.

Thanks for the report anyway :blush:
