### ISSUE TITLE
/web/sign/get_fonts: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#152]
I have created a new copier-template odoo 11 instance, with the actual new version of copier-template, this on the same server  created with previous version of copier-template 

I have inverse proxy version traefik:1.6-alpine

Now when I try to use signature widget i get this error and cannot get it running

¿Is this can be something maybe about traefik version issue?

On my log:

odoo_1                    | 2020-10-23 02:48:38,261 1 INFO servicios odoo.http: <function Binary.get_fonts at 0x7f0bde68f158>, /web/sign/get_fonts: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

**Comment by joao-p-marques** [comment]
Well, that shouldn't be a problem, as the copier template supports both Traefik v1 and v2 labels.

Can you post you Traefik labels configuration? You can anonymize some data if you want...

**Comment by carlosecv** [comment]
labels:
      doodba.domain.main: "servicios.racomx.com"
      traefik.enable: "true"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:servicios.racomx.com;Path:/web{anything:/.*},/website/info{anything:/.*}
      traefik.main-0.frontend.rule: Host:servicios.racomx.com
      traefik.longpolling-0.frontend.rule: Host:servicios.racomx.com;Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.fieldservice2021-13-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.fieldservice2021-13-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.fieldservice2021-13-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.fieldservice2021-13-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.fieldservice2021-13-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.fieldservice2021-13-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.fieldservice2021-13-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.rule:
        Host(`servicios.racomx.com`)
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-main-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.rule:
        Host(`servicios.racomx.com`)
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-main-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.rule:
        Host(`servicios.racomx.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.service:
        fieldservice2021-13-0-prod-longpolling
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-0.middlewares:
        fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.rule:
        Host(`servicios.racomx.com`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.service:
        fieldservice2021-13-0-prod-longpolling
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.middlewares:
        fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-longpolling-secure-0.tls.certResolver:
        letsencrypt
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.rule:
        Host(`servicios.racomx.com`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forbid-crawlers, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`servicios.racomx.com`) && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`, `/website/info`))
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.service:
        fieldservice2021-13-0-prod-main
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.middlewares:
        fieldservice2021-13-0-prod-buffering, fieldservice2021-13-0-prod-compress, fieldservice2021-13-0-prod-forbid-crawlers, fieldservice2021-13-0-prod-forceSecure
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.fieldservice2021-13-0-prod-forbiddenCrawlers-secure-0.tls.certResolver:
        letsencrypt

**Comment by joao-p-marques** [comment]
Thank you.
@Yajo do you think maybe this is, indeed, a problem with Traefik routing? if we need a json request to be proxyed, should we try a TCP router instead? Or does it have to do with the way the request is being made on the client?

**Comment by Yajo** [comment]
This is a programming error not related to doodba.

**Comment by carlosecv** [comment]
But this is the same code and same server, the only difference is that we execute copier-template this days instead the other one  executed 3 months ago...

**Comment by Yajo** [comment]
Duplicate of #166
