### ISSUE TITLE
Populating scaffolding for 14.0, VSCode workspace file is named for 13.0

### ISSUE THREAD

**Issue by pedrobaeza** [Tecnativa/doodba-copier-template#156]
After any of the invoke commands that recreates the file, it is named `doodba.scaffolding-13.code-workspace`.

**Comment by joao-p-marques** [comment]
Hi. I can't replicate this issue.
The VSCode workspace file is generated based on the name of the root folder of your project: https://github.com/Tecnativa/doodba-copier-template/blob/dd5b21f5c84ed681b37555529db1e4ebc191f478/tasks.py.jinja#L43
Maybe you named it `scaffolding-13`?

**Comment by pedrobaeza** [comment]
Indeed I'm not able to reproduce it now. Not sure what happens...
