### ISSUE TITLE
Possible small improvements

### ISSUE THREAD

**Issue by ValentinVinagre** [Tecnativa/doodba-copier-template#16]
Hi @Yajo ,
I would like to comment on some possible small improvements in the copier questions:

1. Optional configurations, as you referenced at https://github.com/Tecnativa/doodba-copier-template/issues/14#issuecomment-604351119
2. Is possible to add optional help (with new command or option) in some questions with more detailed explanation or example?
3. Add a new configuration for odoo enterprise and to add ssh configurations.
4. Add a new configuration for calculate/estimate the  basic user related parameters(for example), following the rules of odoo if you want https://www.odoo.com/documentation/13.0/setup/deploy.html#worker-number-calculation:
- workers
- max_connections
- max-cron-threads
- limit-memory-soft
- limit-memory-hard

What do you think?

Thanks a lot :)

**Comment by Yajo** [comment]
> * Optional configurations, as you referenced at [#14 (comment)](https://github.com/Tecnativa/doodba-copier-template/issues/14#issuecomment-604351119)

This depends on https://github.com/pykong/copier/issues/161 before.

> * Is possible to add optional help (with new command or option) in some questions with more detailed explanation or example?

If needed, I'd go for the simplest path: just drop a doc in [the docs folder](https://github.com/Tecnativa/doodba-copier-template/tree/master/docs) and print the link in the parameter help. Today's terminals allow users to click on links, so they can do it to get further help.

> * Add a new configuration for odoo enterprise and to add ssh configurations.

I have no plans on doing that, but a PR that is well aligned with the project would be welcomed. See #15 also.

> * Add a new configuration for calculate/estimate the  basic user related parameters(for example), following the rules of odoo if you want https://www.odoo.com/documentation/13.0/setup/deploy.html#worker-number-calculation:

It could be good indeed, but again no plans for that. PRs welcome, though :blush:
