### ISSUE TITLE
[Question] why "tecnativa/doodba:${ODOO_VERSION}-onbuild" is downloaded everytime?

### ISSUE THREAD

**Issue by obayit** [Tecnativa/doodba-copier-template#173]
Whenever `invoke img-pull` is run in a new project, docker uses cached images. But when running `invoke img-build --pull` it downloads the `tecnativa/doodba:${ODOO_VERSION}-onbuild` everytime!

How to use cached version for that image too, like the others (mailhog, postgres-autoconf, ..etc)?

**Comment by obayit** [comment]
Ok, I just realised passing `--pull` is the reason that it always downloads the image, even if there is no change!

As mentioned in `docker-compose` [docs](https://docs.docker.com/compose/reference/build/)

**Comment by Yajo** [comment]
Actually it will only check if it has to download it. If there are no changes on the registry, it won't download it.
