### ISSUE TITLE
[Question] How to create a staging instance with doodba?

### ISSUE THREAD

**Issue by obayit** [Tecnativa/doodba-copier-template#179]
Not sure if this is a question, or a feature request.

A staging is a copy of the production database with a PR applied to it from a specific repository.

The "brute force" approach would be to copy the project directory into a new one. Then change the `.copier-answers.yml` values like `domains_prod`, `domains_test`, `postgres_dbname?`. Then add the PR in `repos.yaml`. And finally build and run with `prod.yaml`.

Another approach may be to use a different `.copier-answers.yml` file, and change `repos.yaml` temporarily to add the PR and run a new instance of the `prod.yaml`.

My question is, how to create a staging instance with doodba?

**Comment by pedrobaeza** [comment]
Copy the scaffolding directory, and inside, change docker-compose.yml link from prod.yaml to test.yaml. Then you just need to restore the DB/filestore over it for having a staging system isolated from the outside.

**Comment by obayit** [comment]
Thanks, I didn't even know that `docker-compose.yml` was a link :laughing:
