### ISSUE TITLE
Someone has enabled pgweb ??

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#186]
Someone knows how to enable pgweb?

Thanks

**Comment by joao-p-marques** [comment]
You can take a look at the docs [here](https://github.com/Tecnativa/doodba-copier-template/blob/stable/docs/daily-usage.md#pgweb)

It comes pre-configured for the `devel` environment. on port `${ODOO_MAJOR}081`

**Comment by carlosecv** [comment]
Thanks 

It was just that in previous copier has not been enabled now on recent versions its enabled on devel.yaml

Regards
