### ISSUE TITLE
QUESTION: docker-mailserver SMTP_ONLY postfix-accounts.cf fixed?

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba-copier-template#193]
@Yajo I see a commit for the amavis issues.

In our internal docs we also have a note
https://github.com/tomav/docker-mailserver/issues/1359 
WHenever restarting mail need to run `docker-compose exec smtp touch /tmp/docker-mailserver/postfix-accounts.cf`

Is this still necessary?

**Comment by Yajo** [comment]
I have automated that and haven't tested what happens without the workaround for a long time. The linked issue was closed due to age, not to a fix, so I guess this is still the case, yes.

But maybe you can try and report back?
