### ISSUE TITLE
reCAPTCHA not working

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#207]
I tried to enable reCAPTCHA for Odoo 14 WebSite default Odoo module, but instead a RECAPTCHA image on forms I only get the text:

Protected by reCAPTCHA, Privacy Policy & Terms of Service apply. 

Is something I am missing on labels or another part?

Thanks

**Comment by Yajo** [comment]
This problem is not related to doodba, but to that specific module.
