### ISSUE TITLE
Error installing pycups lib

### ISSUE THREAD

**Issue by manuelcalerosolis** [Tecnativa/doodba-copier-template#210]
Trying to install the library "pycups" simply including in "pip.txt" I get the following error:

creating build/temp.linux-x86_64-3.6
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DVERSION="2.0.1" -I/usr/local/include/python3.6m -c cupsmodule.c -o build/temp.linux-x86_64-3.6/cupsmodule.o
    **unable to execute 'gcc': No such file or directory**
    error: command 'gcc' failed with exit status 1

Possibly I need to add something to the doodba configuration in order to run "gcc". 

Thanks a lot.

**Comment by obayit** [comment]
I tried running gcc from a running doodba odoo container, and it exists.
What are the contents of the `pip.txt`?

**Comment by manuelcalerosolis** [comment]
This is my pip.txt:

git+https://github.com/OCA/openupgradelib.git@master
unicodecsv
unidecode
python-barcode
psycopg2-binary
pysftp==0.2.8
xlsxwriter
xlrd
pyOpenSSL
zeep
qrcode[pil]
xmlsig
cachetools
pycups
pycountry

**Comment by pedrobaeza** [comment]
You need to add in apt_build.txt the cups dev library and on apt.txt, the cups library, but this is not something of Doodba, but a requirement of the cups pip package that you have to do in any system.

**Comment by manuelcalerosolis** [comment]
For pycups this is the content that has worked for me from the apt.txt and apt_build.txt files, maybe it can help someone who tries to install this library.

build-essential
python3-dev
libcups2-dev
