### ISSUE TITLE
error committing new project

### ISSUE THREAD

**Issue by ygol** [Tecnativa/doodba-copier-template#213]
Hi,

I'm getting error committing a new project.

` copier copy gh:Tecnativa/doodba-copier-template ./subproject `
answering the questions.
`git add .`
`git commit -m"Intitial commit"`

```
ygol:subproject/ (master*) $ git commit -m "initial"                                                                                       [13:29:38]
forbidden files......................................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
black....................................................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
prettier + plugin-xml....................................................Failed
- hook id: prettier
- exit code: 2
- files were modified by this hook

test.yaml
.copier-answers.yml
prod.yaml
[error] prod.yaml: SyntaxError: Nested mappings are not allowed in compact mappings (27:37)
[error]   25 |         "X-Robots-Tag:noindex, nofollow"
[error]   26 |       traefik.forbiddenCrawlers-0.frontend.rule: Host:;Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
[error] > 27 |       traefik.main-0.frontend.rule: Host:
[error]      |                                     ^^^^^
[error] > 28 |       traefik.longpolling-0.frontend.rule: Host:;Path:/longpolling/{anything:.*}
[error]      | ^
[error]   29 |       traefik.longpolling-0.port: 8072
[error]   30 |       traefik.forbiddenCrawlers-1.frontend.headers.customResponseHeaders:
[error]   31 |         "X-Robots-Tag:noindex, nofollow"

Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Mixed line ending........................................................Passed
flake8 except __init__.py................................................Passed
flake8 only __init__.py..............................(no files to check)Skipped
pylint with optional checks..............................................Passed
- hook id: pylint
- duration: 1.75s
pylint with mandatory checks.............................................Passed
eslint...............................................(no files to check)Skipped
- hook id: eslint
ygol:subproject/ (master*) $                                                                                                               [13:32:37]

```
Is this a known issue?

I could force the commit (ignoring the pre-commit) but the problem stays when I will have to update copier in the future as the pre-hook will be applied on the 'pulled' updated code.

TIA

**Comment by obayit** [comment]
Looks like wrong answer for the production or testing URLs.

**Comment by ygol** [comment]
tnx @obayit tried various way to add those without success:
domain.tld
"domain.tld"
["domain.tld"]

**Comment by obayit** [comment]
Try this `[{'hosts': ['domain.tld']}]` of course replace `domain.tld` with your domain.

**Comment by ygol** [comment]
> 
> 
> Try this `[{'hosts': ['domain.tld']}]` of course replace `domain.tld` with your domain.
do you mean to use the above as the answer to the copier question? if yes, it also doesn't work :(

**Comment by obayit** [comment]
Can you just confirm that the new answer is in the `.copier-answers.yml` file?
Check if the domain part looks like this:
```
domains_prod:
  - hosts:
      - prod.docker.localhost
domains_test:
  - hosts:
      - test.docker.localhost
```

**Comment by ygol** [comment]
no it is still showing
```
domains_prod:
  - etrog.cloud
```

but when trying to do 'copier update' it fails (snapshot below).

![image](https://user-images.githubusercontent.com/2945174/106393406-986ca780-63ff-11eb-8bd4-03c9cd35f93a.png)

I tried with a new project:

here what I did:
1. copier copy gh:Tecnativa/doodba-copier-template ./subproject
2. answer questions:
     for host I've answered: [{'hosts': ['etrog.cloud']}]
     for test: [{'hosts': ['test.etrog.cloud', 'demo.etrog.cloud']}]
3. cd subproject
4. git add . 
5. git commit -m "Intial doodba commit"

![image](https://user-images.githubusercontent.com/2945174/106393133-01ebb680-63fe-11eb-8a32-6c12c231bb46.png)

6. gir add . (again)
7. git commit -m "Intial doodba commit" (and there it is working)

![image](https://user-images.githubusercontent.com/2945174/106393497-2052b180-6400-11eb-952b-9ea480924d17.png)

**Comment by obayit** [comment]
Well. I am not sure why that is happening!

**Comment by ygol** [comment]
thank you for helping Obay. I will further search.

**Comment by joao-p-marques** [comment]
@ygol on the last example you posted the first commit fails because pre-commit reformats some files. That is the correct flow, as the files generated by copier aren't always correct according to the formatting standards.

On your previous examples, it was, indeed, failing because of a wrong definition of `domains_prod`. As the [help message suggests](https://github.com/Tecnativa/doodba-copier-template/blob/stable/copier.yml#L202), it should be a yaml structure (which is correct on the last example).



> no it is still showing
> 
> ```
> domains_prod:
>   - etrog.cloud
> ```

When you tried to correct the initial error, did you try to update the answers file manually? If you did, that should be what was causing the error of the answers file not changing when you ran `copier update`. All the changes should be done through a `copier update` and answering different values to the questions, not by rewriting the answers file. 

I am closing this, but feel free to ask more questions if you still need help. 🙂
