### ISSUE TITLE
Format of domains_prod question in copier

### ISSUE THREAD

**Issue by rquevedo** [Tecnativa/doodba-copier-template#214]
Hi folks,
When im answer copier questions and get domains_prod. I entered domain.com but environment dont up(docker-compose -f prod.yaml up -d).
Im getting error:
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./prod.yaml", line 27, column 41

Just notice that hosts section is empty because i wrong answer that question. Witch format can be used in that section?

**Comment by obayit** [comment]
Every json is a valid yaml (i guess), for example this is a valid answer `[{'hosts': ['domain.com']}]`

**Comment by joao-p-marques** [comment]
> Every json is a valid yaml

Yes, @obayit is right :smiley: 

The expected structure is something like the example in https://github.com/Tecnativa/doodba-copier-template/blob/stable/copier.yml#L201, so `[{'hosts': ['domain.com']}]` is indeed a good example.

**Comment by rquevedo** [comment]
Thank you @obayit , your answer helps me a lot.
