### ISSUE TITLE
wdb cannot start

### ISSUE THREAD

**Issue by luismata01** [Tecnativa/doodba-copier-template#218]
Hi
I have a fresh install of DOODBA on Ububtu 20.4 my project is  ODOO 14, all work fine but when I try to use wdb on http:localhost:14081 this cannot connect.

![imagen](https://user-images.githubusercontent.com/43929688/108500221-d41fc200-7285-11eb-97ba-9a220eaf7a7c.png)

Thank's a lot for your help

**Comment by pedrobaeza** [comment]
The port is 14069

**Comment by pedrobaeza** [comment]
Sorry, I read incorrectly, reopening.

**Comment by joao-p-marques** [comment]
Yes, still the issue is that the port is different. It should be http://localhost:14984/
