### ISSUE TITLE
Odoo traefik labels

### ISSUE THREAD

**Issue by rquevedo** [Tecnativa/doodba-copier-template#221]
When i update porject using `copier update` or even when create new one from scratch, longpolling entries are not being generated. This cause BUS error in odoo logs.
In other projects this labels are generated normally. Any clue?

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by rquevedo** [comment]
> Odoo version?

13.0

**Comment by joao-p-marques** [comment]
@rquevedo Can you provide your `.copier-answers` file? You can anonymize some data if you want. 
Those entries are only generated with a correct `domains_prod` configuration. Maybe there is something wrong there?

**Comment by rquevedo** [comment]
> @rquevedo Can you provide your `.copier-answers` file? You can anonymize some data if you want.
> Those entries are only generated with a correct `domains_prod` configuration. Maybe there is something wrong there?

`# Changes here will be overwritten by Copier
_commit: v2.6.1
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: true
backup_dst: mega://someuser@mega.nz/BACKUPS/PartnerName
backup_email_from: pname@gmail.com
backup_email_to: pname@gmail.com
backup_tz: UTC
cidr_whitelist: null
domains_prod:
  - hosts:
      - www.pname.com
      - pname.com
    redirect_to: www.pname.com
domains_test: null
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 13.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 13
project_author: Kubux
project_license: OPL-1.0
project_name: pname
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null`

**Comment by joao-p-marques** [comment]
Can you send it inside a code block? It got reformatted and it is hard to see the contents.

**Comment by rquevedo** [comment]
> Can you send it inside a code block? It got reformatted and it is hard to see the contents.

How can skip markdown format? Code block dont help.

**Comment by joao-p-marques** [comment]
You can send it inside a code block with https://www.markdownguide.org/extended-syntax#syntax-highlighting

**Comment by rquevedo** [comment]
> > @rquevedo Can you provide your `.copier-answers` file? You can anonymize some data if you want.
> > Those entries are only generated with a correct `domains_prod` configuration. Maybe there is something wrong there?
> > This is the content of .copier-answers.yml
> 
> ```json
> # Changes here will be overwritten by Copier
> _commit: v2.6.1
> _src_path: gh:Tecnativa/doodba-copier-template
> backup_deletion: true
> backup_dst: mega://someuser@mega.nz/BACKUPS/PartnerName
> backup_email_from: pname@gmail.com
> backup_email_to: pname@gmail.com
> backup_tz: UTC
> cidr_whitelist: null
> domains_prod:
>   - hosts:
>       - www.pname.com
>       - pname.com
>     redirect_to: www.pname.com
> domains_test: null
> gitlab_url: null
> odoo_dbfilter: .*
> odoo_initial_lang: es_ES
> odoo_listdb: false
> odoo_oci_image: null
> odoo_proxy: traefik
> odoo_version: 13.0
> paths_without_crawlers:
>   - /web
>   - /website/info
> postgres_dbname: prod
> postgres_username: odoo
> postgres_version: 13
> project_author: Kubux
> project_license: OPL-1.0
> project_name: pname
> smtp_canonical_default: null
> smtp_canonical_domains: null
> smtp_default_from: null
> smtp_relay_host: null
> smtp_relay_port: 587
> smtp_relay_user: null
> ```

Updated in first comment.

**Comment by rquevedo** [comment]
```json
version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_ES"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: ""
      traefik.enable: "true"
      traefik.domain: ""
      traefik.alt-0.frontend.redirect.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.alt-0.frontend.redirect.replacement: $$1://www.pname.com/$$3
      traefik.alt-0.frontend.rule: Host:www.pname.com, pname.com
      traefik.http.middlewares.Pname-13-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.Pname-13-0-prod-compress.compress: "true"
      ? traefik.http.middlewares.Pname-13-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.middlewares.Pname-13-0-prod-forceSecure.headers.forceSTSHeader: "true"
      traefik.http.middlewares.Pname-13-0-prod-forceSecure.headers.sslRedirect: "true"
      traefik.http.services.Pname-13-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.Pname-13-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.middlewares.Pname-13-0-prod-redirect-0.redirectRegex.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.http.middlewares.Pname-13-0-prod-redirect-0.redirectRegex.replacement: $$1://www.pname.com/$$3
      traefik.http.routers.Pname-13-0-prod-redirect-0.rule:
        Host(`www.pname.com`, `pname.com`)
      traefik.http.routers.Pname-13-0-prod-redirect-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-redirect-0.middlewares:
        Pname-13-0-prod-compress, Pname-13-0-prod-forceSecure,
        Pname-13-0-prod-redirect-0
      traefik.http.routers.Pname-13-0-prod-redirect-secure-0.rule:
        Host(`www.pname.com`, `pname.com`)
      traefik.http.routers.Pname-13-0-prod-redirect-secure-0.service: Pname-13-0-prod-main
      traefik.http.routers.Pname-13-0-prod-redirect-secure-0.middlewares:
        Pname-13-0-prod-compress, Pname-13-0-prod-forceSecure,
        Pname-13-0-prod-redirect-0
      traefik.http.routers.Pname-13-0-prod-redirect-secure-0.tls: "true"
      traefik.http.routers.Pname-13-0-prod-redirect-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

  backup:
    extends:
      file: common.yaml
      service: backup
    env_file:
      - .docker/backup.env
      - .docker/db-access.env
    restart: unless-stopped
    depends_on:
      - db

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  backup_cache:
  filestore:
  db:

```

**Comment by joao-p-marques** [comment]
@rquevedo in the `domains_prod` answer, the structure should be:
```yaml
- hosts:
    - www.pname.com
    - pname.com
- redirect_to: 'www.pname.com'
```
(not another entry inside `hosts`, but another element of the list)

**Comment by rquevedo** [comment]
> @rquevedo in the `domains_prod` answer, the structure should be:
> 
> ```yaml
> - hosts:
>     - www.pname.com
>     - pname.com
> - redirect_to: 'www.pname.com'
> ```
> 
> (not another entry inside `hosts`, but another element of the list)

You are rigth, but im answear this:

```json
[{'hosts': ['www.fotopluscuba.com', 'fotopluscuba.com'], 'redirect_to': 'www.fotopluscuba.com'}]
```
In theory this must generate one entry 'redirect_to' at same level that 'hosts'.

**Comment by joao-p-marques** [comment]
The correct answer would be:
```yaml
[{'hosts': ['www.pname.com', 'pname.com']}, {'redirect_to': 'www.pname.com'}]
```
What we need is a _list of objects_ in yaml, not an object with several keys.

**Comment by rquevedo** [comment]
I see, this should fix the problem. I will try and post feedback. Thank you very mutch.

**Comment by rquevedo** [comment]
> ```yaml
> pname
> ```

Hi @joao-p-marques I tried your answear and i came in new error, something like Host: empty.
I think that finally this will be the correct one:
```yaml
[{'hosts': ['www.pname.com']}, {'hosts': ['pname.com'], 'redirect_to': 'www.pname.com'}]
```
Seems like host key must be in all objects, take a look to this code snipet that coper share in help section:

https://github.com/Tecnativa/doodba-copier-template/blob/32d9d6b3240b14da31e1fe73b68d2b6ed2f27f46/copier.yml?utm_source=Doodba#L201-L219

**Comment by joao-p-marques** [comment]
Sorry, I think I misled you before. Indeed, the correct answer should be a list with those keys, so your last answer should be correct.

**Comment by joao-p-marques** [comment]
Closing this a it seems to be solved. Feel free to reopen if you keep having the same issue

**Comment by rquevedo** [comment]
> Sorry, I think I misled you before. Indeed, the correct answer should be a list with those keys, so your last answer should be correct.

Dont worry, you help me a lot. Thanks again.
