### ISSUE TITLE
Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry.

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#228]
Hello

I want to update my prod.yaml file with a new domain to resolve but I dont know if its ok doit this way:

I updated my hosts parameter on my copier instance already created so i add my new domain to my copier-answers.yml file::

```
domains_prod:
- hosts:
  - myactualdomain.com
  - addnewdomain.com
```
And run again copier with update option

`$ copier -a ../copier-answers.yaml update .`

And after answer all questions I get:

Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry.

I just want to add new domain name hosts to my prod.yaml to correctly resolves the new domain too.

Thank you

**Comment by joao-p-marques** [comment]
Hi. 

There seems to be some confusion when it comes to updating your answers with copier, so we tried to [make it clearer with the latest release.](https://github.com/Tecnativa/doodba-copier-template/blob/stable/%7B%7B%20_copier_conf.answers_file%20%7D%7D.jinja#L1)
Basically, **the answers file should never be edited manually**. That is what copier uses to manage the template and apply it correctly. To update the answers, you should instead run a `copier update` (which will update the template at the same time) but will also re-ask you the questions it needs.

As for the error `Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry`, copier will never perform an update on a dirty repository. No changes should be on the working tree. You should undo your modifications to the answers file, ensure the repo is clean, and run a normal update with new answers.

**Comment by luismata01** [comment]
Hi

I have this same error, after execute copier update

What is the path to resolve this, I don't understand the last explain @joao-p-marques

**Comment by pedrobaeza** [comment]
`git reset --hard` for undoing dirty changes.

**Comment by luismata01** [comment]
Hi @pedrobaeza 

 I try your solution for update the same problem but the result is fail. "Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry."

I need this for update "domains_prod?" is frecuently add more domain in my case and need understand the procedure for  production environment.

Thanks

**Comment by pedrobaeza** [comment]
There are still files modified or added in the repository, and that's why it appears the error. You have to reset any non committed change before running copier.
