### ISSUE TITLE
Regenerate common.yaml and prod.yaml when bucket configuration is added

### ISSUE THREAD

**Issue by HviorForgeFlow** [Tecnativa/doodba-copier-template#232]
Hello there,

I face this problem on one of my projects. I started to develop without s3 backup configuration enabled.
`common.yaml` was created without backup container. Once I wanted to go to production I added the configuration, but unfortunately backup container wasn't created. I had to copy paste from other project until I've got proper configuration.

It would be awesome that no matter my initial configuration I could add bucket variable definition on copier-answers, then run `copier --force` update and got doodba ready for production.

Not sure if it is possible right now, maybe I'm not so experienced with copier

Regards,

**Comment by joao-p-marques** [comment]
Hi :wave: 

That is, indeed, done by copier automatically. However, the copier answers should not be updated manually, but always through a `copier update`. When you run that command, copier will re-ask you the questions (unless you run it with `--force`) so you can change the values.
If you change the copier answers file manually, it will break copier's smart diff mechanism, so you should not do that. As that seems to be a common question, we already added a little warning to the top of the copier answers file: https://github.com/Tecnativa/doodba-copier-template/blob/stable/%7B%7B%20_copier_conf.answers_file%20%7D%7D.jinja#L1
