### ISSUE TITLE
Point of Sale Price lists not working

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#234]
Odoo v14 
copier template
default devel ambient (devel.yaml)

Case:
If you use a Price list that depends on quantity, example:

Product 1 

We add 2 Float fields then we xcreated a Price List:

Price List:
if 1 piece Price By Formula: Custom Float field1: 45
if more than 75 pieces Price By Formula: Custom Float field2: 42

If we do the operation on Sales Order it uses correctly the Price List Formula  but on Point of sale the price used is the Price established on default Price List Product Form.

Price List doesn't update correctly the price by Formula.

Regards

**Comment by pedrobaeza** [comment]
This has nothing to do with Doodba nor DCT.

**Comment by carlosecv** [comment]
Ok 

I thinked on this because on normal odoo installation it works ok but not inside doodba nor in devel.yaml or prod.yaml environments
