### ISSUE TITLE
Remove default db_filter from devel

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/doodba-copier-template#258]
**Is your feature request related to a problem?** 

https://github.com/Tecnativa/doodba-copier-template/commit/eb8f36dbddab084bf168b51a43683cb94cfccaac interrupted the workflow of some devs (@sergio-teruel 👋🏼 😋 ).

**Describe the solution you'd like**

Instead of hardcoding a db filter, if we want `inv test` to not fail on tours when there are multiple dbs, we can add that variable in the test execution, or we can also add `--database` to the `odoo` command being executed, so the db selection is explicit.

**Comment by joao-p-marques** [comment]
Ok, although we will lose another use case where the DB_FILTER came handy: in a public controller endpoint, as the session doesn't know with DB to query, it will fail with 404...

**Comment by Yajo** [comment]
We can't have it all... 🤷🏼‍♂️

**Comment by Yajo** [comment]
FTR, I had the other day a problem because I had 2 databases, and both started with `devel` (to be able to use both from db manager). No way to run tours. Fixing this will be a help in those cases too.
