### ISSUE TITLE
Answer for project_license: "No license" is not rembered

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba-copier-template#265]
## Describe the bug

When using doodba-copier-template to update a project that has no license, the choice `No license` is saved as `project_license: null` in `.copier-answers.yml`.
Now when you run copier again, the default option is not `No license` and you cannot just enter through.

## To Reproduce

**Affected versions**: v.3.0.0

1. copy scaffolding with copier choosing license `No license`
2. update scaffolding with copier

**Expected behavior**
The choice `No license` is remembered as all other answers are.

**Additional context**
As a workarround (even though very much not recomended ;-) ) you can edit .copier-answers.yml manually with:
```
project_license: No license
```

**Comment by Yajo** [comment]
Humm this must be due to #254. What's your copier version please?

**Comment by ap-wtioit** [comment]
Versions according to pipx:
```
   package copier 5.1.0, Python 3.7.3
    - copier
   package docker-compose 1.29.2, Python 3.7.3
    - docker-compose
   package invoke 1.5.0, Python 3.7.3
    - inv
    - invoke
   package pre-commit 2.13.0, Python 3.7.3
    - pre-commit
    - pre-commit-validate-config
    - pre-commit-validate-manifest
```
