### ISSUE TITLE
ERROR: Network "inverseproxy_shared" needs to be recreated - option "encrypted" has changed

### ISSUE THREAD

**Issue by luismata01** [Tecnativa/doodba-copier-template#271]
After use the template for production server I cannot Up the Traeffik Docker container show this error:
ERROR: Network "inverseproxy_shared" needs to be recreated - option "encrypted" has changed

ODOO v14 CE

**Comment by carlosecv** [comment]
Try:

docker-compose -f prod.yaml down ; docker-compose -f prod.yaml build --no-cache ; docker-compose -f prod.yaml up --build --remove-orphans --force-recreate -d

**Comment by luismata01** [comment]
I try your recommendation @carlosecv but is the same problem not work Traeffik only odoo container
I run  this command
docker-compose -p inverseproxy -f inverseproxy.yaml up -d

And this  reproduced  the error:
ERROR: Network "inverseproxy_shared" needs to be recreated - option "encrypted" has changed

**Comment by carlosecv** [comment]
Did you created the traefik global proxy previously?

**Comment by luismata01** [comment]
> Did you created the traefik global proxy previously?

Yes, If you talk about the inverseproxy.yaml

**Comment by pedrobaeza** [comment]
As the message says, you have changed such option without recreating the instance. Just do `docker-compose down` and the `docker-compose up -d` for recreating the instance.

**Comment by luismata01** [comment]
> Just do `docker-compose down` and the `docker-compose up -d` for recreating the instance.

Excuse me @pedrobaeza but I try your solution and the other from @carlosecv and I have the same problem after that.

**Comment by pedrobaeza** [comment]
Then you are not recreating it correctly. Try restarting the server. Anyways, this is not an issue of the project.
