### ISSUE TITLE
Release 4.1.0?

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/doodba-copier-template#318]
[There are already a lot of changes since last release](https://github.com/Tecnativa/doodba-copier-template/compare/v4.0.0...60c5b3c7febd4300e23b379ed77fd9cd7bf493b0), and no further activity recently.

Could you please tag a new release?

**Comment by pedrobaeza** [comment]
Done: https://github.com/Tecnativa/doodba-copier-template/releases/tag/v4.1.0
