### ISSUE TITLE
[v14 CE] ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by luismata01** [Tecnativa/doodba-copier-template#323]
Hi Team

After install all  the  Python CLI apps, and When I Use the template to generate my subproject, appear the error 
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.local/p                                                                                                          ipx/venvs/copier/lib/python3.8/site-packages/markupsafe/__init__.py)

How I show in the Image attached.

![image](https://user-images.githubusercontent.com/43929688/157134722-66b1e45f-a61d-40cc-9ef3-3f224478300b.png)

**Comment by pedrobaeza** [comment]
I don't think this a bug in this template, but your system. Try `pip3 install --force-reinstall MarkupSafe==2.0.1`

**Comment by luismata01** [comment]
> 

Hi @pedrobaeza 

I try with your recomendations, but I have the same error

![image](https://user-images.githubusercontent.com/43929688/157303900-02c0df96-0bbd-48a0-96b1-344bbdd3c2a3.png)

**Comment by pedrobaeza** [comment]
Well, it came from a search on Internet about the problem, but I don't know anything more, as we are not facing this problem.

**Comment by vanderleiromera** [comment]
Uninstall pipx version current and  install pipx 0.16.5

**Comment by luismata01** [comment]
In this moment I resolve this with this solution
https://github.com/copier-org/copier/issues/574#issuecomment-1046708983

 Thanks to all for your attention and support
