### ISSUE TITLE
openupgradelib not cloned in container

### ISSUE THREAD

**Issue by bassbassbuff** [Tecnativa/doodba-copier-template#368]
pipx list
apps are exposed on your $PATH at /home/thedude/.local/bin
   package copier 7.0.1, installed using Python 3.10.6
    - copier
   package invoke 2.0.0, installed using Python 3.10.6
    - inv
    - invoke
   package pre-commit 3.0.4, installed using Python 3.10.6
    - pre-commit
  
Subproject created with
copier -r HEAD copy gh:Tecnativa/doodba-copier-template ~/Development/odoo/odoo15

Installed Docker Desktop for linux with docker compose v2

OS = Ubuntu 22.04

Expected to build and run Odoo in development env.

invoke img-build --pull
invoke git-aggregate

Throws below Traceback

~/Development/odoo/odoo15$ invoke img-build --pull
[+] Building 19.1s (9/9) FINISHED                                                                                         
 => [internal] load build definition from Dockerfile                                                                 0.0s
 => => transferring dockerfile: 31B                                                                                  0.0s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 34B                                                                                     0.0s
 => [internal] load metadata for ghcr.io/tecnativa/doodba:15.0-onbuild                                               6.7s
 => [1/1] FROM ghcr.io/tecnativa/doodba:15.0-onbuild@sha256:10c6433390a29a1afe73f7736ad11cb0e9bbe7f2c7c142af1411bd2  0.0s
 => [internal] load build context                                                                                    0.0s
 => => transferring context: 983B                                                                                    0.0s
 => CACHED [2/1] RUN groupadd -g 1000 odoo -o     && useradd -l -md /home/odoo -s /bin/false -u 1000 -g 1000 odoo    0.0s
 => CACHED [3/1] COPY --chown=root:odoo ./custom /opt/odoo/custom                                                    0.0s
 => CACHED [4/1] RUN mkdir -p /opt/odoo/custom/ssh             && ln -s /opt/odoo/custom/ssh ~root/.ssh              0.0s
 => ERROR [5/1] RUN /opt/odoo/common/build && sync                                                                  12.1s
------                                                                                                                    
 > [5/1] RUN /opt/odoo/common/build && sync:                                                                              
#0 0.458 doodba WARNING: Not aggregating code repositories                                                                
#0 0.541 doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/apt_build.txt                    
#0 0.542 doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/apt.txt                          
#0 0.542 doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/gem.txt                          
#0 0.542 doodba INFO: No installable requirements found in /opt/odoo/custom/dependencies/npm.txt
#0 0.543 doodba INFO: Executing: ['pip', 'install', '--no-cache-dir', '-r', '/opt/odoo/custom/dependencies/pip.txt']
#0 1.182 Collecting git+https://github.com/OCA/openupgradelib.git@master (from -r /opt/odoo/custom/dependencies/pip.txt (line 1))
#0 1.184   Cloning https://github.com/OCA/openupgradelib.git (to revision master) to /tmp/pip-req-build-jg_nk8p6
#0 1.190   Running command git clone --filter=blob:none --quiet https://github.com/OCA/openupgradelib.git /tmp/pip-req-build-jg_nk8p6
#0 11.23   fatal: unable to access 'https://github.com/OCA/openupgradelib.git/': Could not resolve host: github.com
#0 11.24   error: subprocess-exited-with-error
#0 11.24   
#0 11.24   × git clone --filter=blob:none --quiet https://github.com/OCA/openupgradelib.git /tmp/pip-req-build-jg_nk8p6 did not run successfully.
#0 11.24   │ exit code: 128
#0 11.24   ╰─> See above for output.
#0 11.24   
#0 11.24   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 11.24 error: subprocess-exited-with-error
#0 11.24 
#0 11.24 × git clone --filter=blob:none --quiet https://github.com/OCA/openupgradelib.git /tmp/pip-req-build-jg_nk8p6 did not run successfully.
#0 11.24 │ exit code: 128
#0 11.24 ╰─> See above for output.
#0 11.24 
#0 11.24 note: This error originates from a subprocess, and is likely not a problem with pip.
#0 11.95 WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
#0 11.95 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#0 12.06 Traceback (most recent call last):
#0 12.06   File "/opt/odoo/common/build.d/200-dependencies", line 19, in <module>
#0 12.06     install(name, req_file)
#0 12.06   File "/usr/local/lib/python3.8/site-packages/doodbalib/installer.py", line 119, in install
#0 12.06     return INSTALLERS[installer](file_path).install()
#0 12.06   File "/usr/local/lib/python3.8/site-packages/doodbalib/installer.py", line 32, in install
#0 12.06     return not self._run_command(self._install_command + self._requirements)
#0 12.06   File "/usr/local/lib/python3.8/site-packages/doodbalib/installer.py", line 22, in _run_command
#0 12.06     return check_call(command, shell=isinstance(command, str))
#0 12.06   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#0 12.06     raise CalledProcessError(retcode, cmd)
#0 12.06 subprocess.CalledProcessError: Command '['pip', 'install', '--no-cache-dir', '-r', '/opt/odoo/custom/dependencies/pip.txt']' returned non-zero exit status 1.
#0 12.08 Traceback (most recent call last):
#0 12.08   File "/opt/odoo/common/build", line 30, in <module>
#0 12.08     subprocess.check_call(command)
#0 12.08   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#0 12.08     raise CalledProcessError(retcode, cmd)
#0 12.08 subprocess.CalledProcessError: Command '/opt/odoo/common/build.d/200-dependencies' returned non-zero exit status 1.
------
failed to solve: executor failed running [/bin/sh -c /opt/odoo/common/build && sync]: exit code: 1

**Comment by bassbassbuff** [comment]
System information lsb_release -a:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by pedrobaeza** [comment]
Temporary glitch or your system doesn't have access to github.com:

```
#0 11.23 fatal: unable to access 'https://github.com/OCA/openupgradelib.git/': Could not resolve host: github.com
```

Nothing to do with Doodba itself.
