### ISSUE TITLE
Odoo 16 build failed: 503 unavailable

### ISSUE THREAD

**Issue by SapphireHotS** [Tecnativa/doodba-copier-template#372]
## Describe the bug

Odoo fails to build odoo 16 image: "ERROR: failed to solve: ghcr.io/tecnativa/doodba:16.0-onbuild: pulling from host ghcr.io failed with status code [manifests 16.0-onbuild]: 503 Service Unavailable"

## To Reproduce

**Affected versions**:

1. Start a new odoo 16 project
2. Execute invoke img-build --pull
3. ERROR: failed to solve: ghcr.io/tecnativa/doodba:16.0-onbuild: pulling from host ghcr.io failed with status code [manifests 16.0-onbuild]: 503 Service Unavailable

**Expected behavior**

Odoo docker should build normally

**Additional context** 

Docker version 23.0.1, build a5ee5b1
docker-compose version 1.29.2

**Comment by pedrobaeza** [comment]
GitHub is having problems: https://www.githubstatus.com/

Wait until it's resolved.

**Comment by SapphireHotS** [comment]
Oh, didn't know that, I submitted the issue because version 15 works fine.

Thanks!
