### ISSUE TITLE
[16.0-onbuild] Fails to build: "denied"

### ISSUE THREAD

**Issue by AaronHForgeFlow** [Tecnativa/doodba-copier-template#385]
## Describe the bug

Can't build image 16.0-onbuild image, it fails rapidly with this error:
```

odoo@odoo ~/16-doodba> invoke img-build --pull
db uses an image, skipping
pgweb uses an image, skipping
smtp uses an image, skipping
wdb uses an image, skipping
proxy_cdnjs_cloudflare_com uses an image, skipping
proxy_fonts_googleapis_com uses an image, skipping
proxy_fonts_gstatic_com uses an image, skipping
proxy_www_google_com uses an image, skipping
proxy_www_googleapis_com uses an image, skipping
proxy_www_gravatar_com uses an image, skipping
odoo_proxy uses an image, skipping
Building odoo
Step 1/2 : ARG ODOO_VERSION
Step 2/2 : FROM ghcr.io/tecnativa/doodba:${ODOO_VERSION}-onbuild
ERROR: Service 'odoo' failed to build: Head "https://ghcr.io/v2/tecnativa/doodba/manifests/16.0-onbuild": denied: denied
```

## To Reproduce

Clone this repo. Follow instructions:

```
python3 -m pip install --user pipx
pipx install docker-compose
pipx install copier
pipx install invoke
pipx install pre-commit
pipx ensurepath
```
and
`copier copy gh:Tecnativa/doodba-copier-template ~/path/to/your/subproject` selecting Odoo 16.0 and leave all the other parameters as default.

finally try to build the project

```
invoke develop
invoke img-build --pull
```

**Expected behavior** It fetches the image 16.0-onbuild and builds it.

This is very likely my fault, but I can't figure it out what I am doing wrong. Thanks for the help, and sorry for the noise in case this is my fault. When doing copier update, it works fine for Odoo 15.0.

**Comment by pedrobaeza** [comment]
This seems that you haven't login in the registry: `docker login ...` or a temporary resource problem.

**Comment by AaronHForgeFlow** [comment]
I am getting trouble to do docker login, not sure if temporary issue, I will check after a while.

**Comment by AaronHForgeFlow** [comment]
It was my fault, fixed after logout/login again, sorry for the noise
