### ISSUE TITLE
Using Debian Stretch, which was released in 2017 and reached its end of life in mid-2022

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#388]
I executed on my coipier template productive environment for odoo version 11:

docker-compose -f prod.yaml down ; docker-compose -f prod.yaml build --no-cache ; docker-compose -f prod.yaml up --build --remove-orphans --force-recreate -d

## Describe the bug

I get this error lines that doesnt let me go on line again:

W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages  404  Not Found [IP: 87.238.57.227 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 30, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/common/build.d/250-postgres-client' returned non-zero exit status 100
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1

## To Reproduce

**Affected versions**: Odoo v11

1. Execute de commands
2. Get Bug

**Expected behavior** 

It must update modules and allow to run odoo v11

It appears that the repositories for Debian Stretch are not accessible or do not have the required files.

The error messages indicate that the following repositories are encountering problems:

http://security.debian.org/debian-security stretch/updates
http://deb.debian.org/debian stretch
http://deb.debian.org/debian stretch-updates
http://apt.postgresql.org/pub/repos/apt stretch-pgdg
The errors "404 Not Found" suggest that the repository URLs are incorrect or the specified distributions (stretch) are no longer available. Since the error messages mention "stretch," it seems that you are using Debian Stretch, which was released in 2017 and reached its end of life in mid-2022.

Debian Stretch is no longer supported, and its repositories might have been removed or archived. It's recommended to upgrade to a supported version of Debian, such as Debian Buster or Debian Bullseye, to ensure you have access to updated packages and security patches.

Any sugestions to solve this? because I cant even update modules 
Thank you

**Comment by chienandalu** [comment]
This was addressed recently. Update your doodba image. https://github.com/Tecnativa/doodba/commit/039f3b401ab009c32a03fac632a368b0f17e1e24

**Comment by carlosecv** [comment]
chienandalu thank you how can I update my doodba on a created instance?

**Comment by pedrobaeza** [comment]
docker-compose pull
