### ISSUE TITLE
Cannot run copier  - ImportError: cannot import name '_PathValueError' from 'pydantic.errors'

### ISSUE THREAD

**Issue by luismata01** [Tecnativa/doodba-copier-template#392]
I update copier because copier copy need new release of copier

But after apply this and review the solution in #367 but I have the same problem

> Traceback (most recent call last):
>   File "/home/luis/.local/bin/copier", line 5, in <module>
>     from copier.__main__ import copier_app_run
>   File "/home/luis/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/__init__.py", line 6, in <module>
>     from .main import *  # noqa: F401,F403
>   File "/home/luis/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 29, in <module>
>     from .errors import (
>   File "/home/luis/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/errors.py", line 6, in <module>
>     from pydantic.errors import _PathValueError
> ImportError: cannot import name '_PathValueError' from 'pydantic.errors' (/home/luis/.local/pipx/venvs/copier/lib/python3.8/site-packages/pydantic/errors.py

Can you help me please

**Comment by Saran440** [comment]
@luismata01 Hi, I found it too in ubuntu 22.04 (python 3.10)

I fixed it by downgrade
- `copier` to version 7.0.1
- `pydantic` to version 1.10.9

**Comment by luismata01** [comment]
> [Saran440](/Saran440)
I try this but is the same result

**Comment by luismata01** [comment]
I resolve this issue with this solution

https://github.com/copier-org/copier/issues/1225#issuecomment-1616656418
