### ISSUE TITLE
[suggestion] Enhancing tasks.py Organization by Implementing Namespaces/Collections for Separate Files

### ISSUE THREAD

**Issue by antoniospneto** [Tecnativa/doodba-copier-template#436]
**Is your feature request related to a problem?**

I end up adding many custom project tasks in the tasks.py, but the file is very large and it's hard to keep it organized.

**Describe the solution you'd like**

I would like to be able to separate/organize tasks into different files.

**Describe alternatives you've considered**

Split the tasks.py into different files using the namespaces/collections feature of the invoker:
https://docs.pyinvoke.org/en/stable/concepts/namespaces.html

**Comment by yajo** [comment]
Ideally, there should be a pip-installable separate project called `doodba-sdk` or similar, so we shouldn't need a `tasks.py` file copied over and over. Also we wouldn't even need invoke.
