### ISSUE TITLE
 Automatic code fix stops working due to vscode update

### ISSUE THREAD

**Issue by pleirb** [Tecnativa/doodba-copier-template#460]
When starting vscode in a doodba copier template project, this appears in the lower right corner:

![image](https://github.com/Tecnativa/doodba-copier-template/assets/2092475/fc3f704e-a404-4c72-a647-98f3f19f0945)
Translation: You have stopped using linting or formatting settings for Python. See logs for more details.
And it directs us to this link: [https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions)

Removing these two lines from **doodba.XXX.code-workspace**: 
```
"python.linting.flake8Enabled": true,
"python.linting.pylintEnabled": true
```
The message disappears, but continues without the useful correction functionality

**Comment by yajo** [comment]
Probably it will have to integrate with https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff now and remove those old linters.

**Comment by pleirb** [comment]
> Probablemente tendrá que integrarse con https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff ahora y eliminar esos viejos linters.

If I find a solution I will publish it, but studying vscode in depth is another of my pending subjects.

**Comment by pleirb** [comment]
> > Probablemente tendrá que integrarse con https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff ahora y eliminar esos viejos linters.
> 
> If I find a solution I will publish it, but studying vscode in depth is another of my pending subjects.

I found a temporary solution, but it would be nice to have some expert confirm if it is the right way to go.
First, add `"charliermarsh.ruff"` to the extensions list in `./vscode/extensions.json`
Second, install Ruff on the system. In my case, Ubuntu is in version 23.10, and I must do it with:
`sudo snap install ruff`
Although I have seen that it is possible in other distributions to do it with pip
Third, remove all the obsolete lines (the ones that are marked off) in the file: `doodba.xxx.code-workspace`
```
    "python.formatting.provider": "none",
    "python.linting.flake8Enabled": true,
    "python.linting.ignorePatterns": [
      "/path/to/your/project/odoo/custom/src/odoo/**/*.py"
    ],
    "python.linting.pylintArgs": [
      "--init-hook=\"import sys;sys.path.append('/path/to/your/project/odoo/custom/src/odoo')\"",
      "--load-plugins=pylint_odoo"
    ],
    "python.linting.pylintEnabled": true,
```
Fourth, uninstall the extensions
`ms-python.pylint` and `ms-python.flake8`

**Comment by pleirb** [comment]
Hello community! Question, is there any intention to repair the code-workspace extension file to fix the problems that appear with the latest version of Visual Studio Code (1.90.1)?

![imagen](https://github.com/Tecnativa/doodba-copier-template/assets/2092475/c62b62fe-cd73-43e9-812e-b4adfa416e62)

Currently it does not correct my code as it should and I am not being able to debug correctly

**Comment by pleirb** [comment]
Thanks, at the moment what version of Visual Studio Code is recommended to use without problems?

**Comment by pedrobaeza** [comment]
I'm using with the latest and I have warnings and errors. Which ones do you mean?

![imagen](https://github.com/Tecnativa/doodba-copier-template/assets/7165771/63f4a6f2-b6f1-4ae5-aae9-912748ab68c1)

**Comment by pleirb** [comment]
The problems that appear are from library imports and therefore the correction is wrong. I guess it has to do with the `linting` problem

![imagen](https://github.com/Tecnativa/doodba-copier-template/assets/2092475/684e5413-62e7-4ced-a781-30526f67b352)

**Comment by pedrobaeza** [comment]
But if I'm not wrong, this wasn't working before either.

**Comment by pleirb** [comment]
> Pero si no me equivoy, esto tampoco estaba funcionando antes.

And what advantage of use could Visual Studio Code have if it is integrated into the code-workspace file generated by dodba copier template if ruff is integrated and the old linters are eliminated as suggested by @yajo

**Comment by pedrobaeza** [comment]
ruff is one thing, and `import` sentences another different one.

**Comment by pleirb** [comment]
> Ruff es una cosa, y `import`oro a otra diferente.

Sorry for my ignorance, yes, it is a code formatter, the thing is that I assumed that this tool works well if it manages to import all the libraries and maybe it had some automatic way to do it or based on the configuration file (code- workspace)

**Comment by pedrobaeza** [comment]
`ruff` is run when you run manually pre-commit or automatic if you configure the repository, but it's not directly attached to VSCode IDE. You may want to do it on IDE file save, but it's not put (it was not either when using previous linter + formatter, as having pre-commit is enough).

**Comment by pleirb** [comment]
> `ruff`se ejecuta cuando se ejecuta manualmente pre-commito o automático si configura el repositorio, pero no está conectado directamente a VSCode IDE. Usted puede querer hacerlo en el archivo IDE guardado, pero no se pone (no fue ni cuando se usaba linter anterior formatter, ya que tener pre-comprometer es suficiente).

Thanks, for the moment then I guess I won't miss anything if I remove the flake8Enabled, pylintEnabled lines from the code-workspace file and the chrome extension from .vscode/extensiions.json
These two things are what were bothering me with warnings when launching Visual Studio Code every day

**Comment by pleirb** [comment]
After so much time it seems that uninstalling the ms-python.python extension and installing it again apparently causes ms-python.black-formatter to also be installed, thus solving the warning problem
