### ISSUE TITLE
Adjust the number of questions depending on the environment to be used (development or test/production)

### ISSUE THREAD

**Issue by pleirb** [Tecnativa/doodba-copier-template#461]
The problem is developed in the following post: #456

It would be useful and clearer if the number of questions can be adjusted depending on the environment to be used (development or test/production), making it clear that they are two totally different things. Even the copier might resolve not to copy prod.yaml and test.yaml if the chosen mode is development, for example.

**Comment by pedrobaeza** [comment]
This can't be done while `copier` doesn't support it.
