### ISSUE TITLE
PDF report not working properly

### ISSUE THREAD

**Issue by busybee-darmen** [Tecnativa/doodba-copier-template#480]
## PDF report not working properly even though the system parameter is correctly set.
![image](https://github.com/Tecnativa/doodba-copier-template/assets/142184588/7c27e7c5-6beb-44b4-abd6-47218a32754a)

I already tried the solution suggested in this issue but still can't make the PDF work properly.
https://github.com/Tecnativa/doodba-copier-template/issues/53

**Affected versions**: 16
**Environment**: Development in local machine

**Comment by pedrobaeza** [comment]
Well, that's the way to work. Maybe remove the final slash.

**Comment by busybee-darmen** [comment]
@pedrobaeza I removed the final slash and then logged out and then restarted the container. And then re-login but still PDF report is displayed incorrectly.

![image](https://github.com/Tecnativa/doodba-copier-template/assets/142184588/a806c197-618d-4bce-8f1c-0e41c20ead2b)

**Comment by agenteAND** [comment]
Hello, the same error here:

```
2024-07-04 06:02:03,293 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web/assets/11489-de3508a/web.report_assets_pdf.min.css HTTP/1.1" 404 - 1 0.011 0.056
odoo-1  | 2024-07-04 06:02:03,295 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web/assets/11507-28e0575/web.report_assets_common.min.css HTTP/1.1" 404 - 1 0.017 0.049
odoo-1  | 2024-07-04 06:02:03,331 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET / HTTP/1.1" 303 - 1 0.009 0.022
odoo-1  | 2024-07-04 06:02:03,402 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web HTTP/1.1" 303 - 2 0.018 0.047
odoo-1  | 2024-07-04 06:02:04,550 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:04] "GET /web/database/selector HTTP/1.1" 200 - 8 0.049 1.097
odoo-1  | 2024-07-04 06:02:05,609 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:05] "GET /web/assets/11489-de3508a/web.report_assets_pdf.min.css HTTP/1.1" 404 - 1 0.014 0.032
odoo-1  | 2024-07-04 06:02:05,617 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:05] "GET /web/assets/11507-28e0575/web.report_assets_common.min.css HTTP/1.1" 404 - 1 0.010 0.038
odoo-1  | 2024-07-04 06:02:06,657 1 WARNING prod odoo.addons.base.models.ir_actions_report: wkhtmltopdf: Exit with code 1 due to network error: ContentNotFoundError
```

wkhtmltopdf doesn't find some assets, despite report.url being set with https://localhost:8069, in a droplet used for dev and testing, in the past, it was working but now it is not.

**Comment by pedrobaeza** [comment]
@busybee-darmen in your screenshot, I see that you have installed some extra modules to give enterprise appearance. Why don't you try with a fresh install without that complements?

**Comment by busybee-darmen** [comment]
> @busybee-darmen in your screenshot, I see that you have installed some extra modules to give enterprise appearance. Why don't you try with a fresh install without that complements?

@pedrobaeza It was working last week on my local machine even though there are enterprise modules installed.

Also, this only happens in the development environment. While in our production server, it does work properly.

**Comment by pedrobaeza** [comment]
Well, you have to check what you have changed in between. Something done broke it.

**Comment by busybee-darmen** [comment]
> Hello, the same error here:
> 
> ```
> 2024-07-04 06:02:03,293 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web/assets/11489-de3508a/web.report_assets_pdf.min.css HTTP/1.1" 404 - 1 0.011 0.056
> odoo-1  | 2024-07-04 06:02:03,295 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web/assets/11507-28e0575/web.report_assets_common.min.css HTTP/1.1" 404 - 1 0.017 0.049
> odoo-1  | 2024-07-04 06:02:03,331 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET / HTTP/1.1" 303 - 1 0.009 0.022
> odoo-1  | 2024-07-04 06:02:03,402 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:03] "GET /web HTTP/1.1" 303 - 2 0.018 0.047
> odoo-1  | 2024-07-04 06:02:04,550 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:04] "GET /web/database/selector HTTP/1.1" 200 - 8 0.049 1.097
> odoo-1  | 2024-07-04 06:02:05,609 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:05] "GET /web/assets/11489-de3508a/web.report_assets_pdf.min.css HTTP/1.1" 404 - 1 0.014 0.032
> odoo-1  | 2024-07-04 06:02:05,617 1 INFO ? werkzeug: 127.0.0.1 - - [04/Jul/2024 06:02:05] "GET /web/assets/11507-28e0575/web.report_assets_common.min.css HTTP/1.1" 404 - 1 0.010 0.038
> odoo-1  | 2024-07-04 06:02:06,657 1 WARNING prod odoo.addons.base.models.ir_actions_report: wkhtmltopdf: Exit with code 1 due to network error: ContentNotFoundError
> ```
> 
> wkhtmltopdf doesn't find some assets, despite report.url being set with https://localhost:8069, in a droplet used for dev and testing, in the past, it was working but now it is not.

I got the same error in the logs.

**Comment by pedrobaeza** [comment]
What do you mean by "droplet"?

**Comment by agenteAND** [comment]
Digital Ocean Droplet

**Comment by pedrobaeza** [comment]
Well, maybe there's a limitation there. Try on local host if it's working properly. I have no more clues for now.

**Comment by busybee-darmen** [comment]
I'm closing this issue.

Solution: Delete all the local database and restore a new database.
