### ISSUE TITLE
Question: How to restore a pg_restore on postgreSQL database

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#50]
I have a pg_dump file that normally I restore it to postgresql from command line with command:

pg_restore -d **odoo_database** odoo_database.sqldump

and finally I do a 

psql -d **odoo_database** 

To alter database ownership and the ownership of all objects inside:

ALTER DATABASE **odoo_database** OWNER TO **pg_user**;

UPDATE pg_class SET relowner = (SELECT oid FROM pg_roles WHERE rolname = '**pg_user**') 
WHERE relname IN (SELECT relname FROM pg_class, pg_namespace 
WHERE pg_namespace.oid = pg_class.relnamespace AND pg_namespace.nspname = 'public');

¿How can i achieve this with copier created project?

**Comment by Yajo** [comment]
Just run `docker-compose run --rm odoo bash` and execute your known commands in that shell :wink:

**Comment by carlosecv** [comment]
O i see thank you very much!!!
