### ISSUE TITLE
Odoo 8 creation error 404  Not Found [IP: 151.101.66.132 80]

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#503]
When you try to do a 

copier copy gh:Tecnativa/doodba-copier-template ~/new_project

## Describe the bug

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

Ign http://security.debian.org jessie/updates InRelease
Ign http://security.debian.org jessie/updates Release.gpg
Ign http://security.debian.org jessie/updates Release
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  
Err http://security.debian.org jessie/updates/main amd64 Packages
  404  Not Found [IP: 151.101.66.132 80]
Get:1 https://deb.nodesource.com jessie InRelease [4607 B]
Ign http://deb.debian.org jessie InRelease
Get:2 https://apt-archive.postgresql.org jessie-pgdg-archive InRelease [4697 B]
Ign http://deb.debian.org jessie Release.gpg
Ign http://deb.debian.org jessie Release
Err http://deb.debian.org jessie/main amd64 Packages
  
Err http://deb.debian.org jessie/main amd64 Packages
  
Err http://deb.debian.org jessie/main amd64 Packages
  
Err http://deb.debian.org jessie/main amd64 Packages
  
Err http://deb.debian.org jessie/main amd64 Packages
  404  Not Found
Get:3 https://deb.nodesource.com jessie/main Sources [20 B]
Get:4 https://apt-archive.postgresql.org jessie-pgdg-archive/main Sources [422 kB]
Get:5 https://deb.nodesource.com jessie/main amd64 Packages [1005 B]
Get:6 https://apt-archive.postgresql.org jessie-pgdg-archive/main amd64 Packages [1142 kB]
Fetched 1575 kB in 13s (116 kB/s)
W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.66.132 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 30, in <module>
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/custom/build.d/20-update-pg-repos' returned non-zero exit status 100
The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1
ERROR: Service 'odoo' failed to build : Build failed

## To Reproduce

Do
copier copy gh:Tecnativa/doodba-copier-template ~/new_project
Then 

docker-compose -f prod.yaml down ; docker-compose -f prod.yaml build --no-cache ; docker-compose -f prod.yaml up --build --remove-orphans --force-recreate -d

**Affected versions**:
Odoo 8 

1.
2.
3.

**Expected behavior** Continue to build whitout errors

**Additional context** 

Docker version 24.0.7, build 24.0.7-0ubuntu4.1
copier 9.2.0

**Comment by pedrobaeza** [comment]
You can't build 8.0 images, as Debian has removed the repositories. You have to look for any mirror of their packages, and you can contribute changing the package sources in the Doodba definition.

**Comment by carlosecv** [comment]
Thank you Pedro but I dont know how  can achieve change the package sources in the Doodba definition
