### ISSUE TITLE
Unable to Load views_migration_17 in Doodba Development Environment

### ISSUE THREAD

**Issue by rrebollo** [Tecnativa/doodba-copier-template#509]
## Issue Description

When attempting to load the [`views_migration_17`](https://github.com/OCA/server-tools/tree/d765715cf3818ea0ea4cf145fd0039a84df4c0e2/views_migration_17) module in a Doodba Odoo 17.0 development environment, the operation fails with the following error:

`ERROR devel odoo.addons.views_migration_17.patch_xml_import: FAIL ! [target_addon] (/opt/odoo/auto/addons/[some xml in target_addon]) [Errno 30] Read-only file system: '/opt/odoo/auto/addons/[some xml in target_addon]`

The [`views_migration_17`](https://github.com/OCA/server-tools/tree/d765715cf3818ea0ea4cf145fd0039a84df4c0e2/views_migration_17) module is designed to address issues with the `attrs` attribute in XML views during migrations from Odoo versions prior to v17.

## Steps to Reproduce

**Affected Version:** Odoo 17.0  

**Reproduction Steps:**

1. Set up an Odoo 17.0 development environment using [Doodba](https://github.com/Tecnativa/doodba). 
2. Add to addons.yaml:
```yaml
server-tools: '*'
```
4. Run:
```bash
inv git-aggregate
```
5. Run:
```bash
docker compose run --rm odoo odoo -d devel -i [some addon you want to fix] --load=base,web,views_migration_17 --stop-after-init
```
6. Observe the error message.

## Additional Context
This issue appears to be linked to the read-only nature of the /opt/odoo/auto/addons/ directory in the Doodba setup.

A similar problem was reported in OCA/server-tools#2793

## Expected Outcome
A workaround or hack to be able to load views_migration_17.

**Comment by pedrobaeza** [comment]
This is not a problem of the Doodba copier template, but the module. The module should allow to write on another path, and thus, you invoke it adding a volume with rw permissions.
