### ISSUE TITLE
Private Repositories multiple modules inside project

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#51]
I tryed to put my modules on:

project/odoo/custom/src/private

If i put each module or addon inside private there is no problem like this:

private/
           |-  module_one/
           |- module_two/
           |- ...

git-aggregate do right the job  but, if try to get a hole project inside private like:

private/
       |- modules_project/
                       |-  module_one/
                       |- module_two/
                       |- ...

invoke git-aggregate cant link modules inside private/modules_project/

**Comment by pedrobaeza** [comment]
That's not possible: you have to put in private the modules in first level folder. There's no sense any way to put several folders there. It's the private part, which should tend to be minimal.

**Comment by carlosecv** [comment]
Well if you have an app with multiple modules it can be very functional,  I see the utility to do it because I have a repo on a private gitlab and cannot get it to work on copier, maybe I’m missing something to get it working the right way

**Comment by pedrobaeza** [comment]
Well, the requirement is to have all modules in first level, so you have to adapt your folder layout to that requirement.

**Comment by carlosecv** [comment]
Excelent thank you Manuel
