### ISSUE TITLE
My gitlab repository is not getting cloned with invoke git-aggregate

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#52]
I received this errors when i do invoke git-aggregate:

```
Please make sure you have the correct access rights
and the repository exists.
(ERROR) [13:50:26] git_aggregator.repo  odoo_web_login   /opt/odoo/custom/src/odoo_web_login> error calling ('git', 'fetch', '--depth', '100', 'origin', '11.0')
Host key verification failed.
fatal: Could not read from remote repository.
```

I created my config under my `project/odoo/custom/ssh/config`:

```
Host realsystems.ddns.net
    HostName realsystems.ddns.net
    Port 2239
    User git
    IdentityFile /opt/odoo/custom/ssh/id_rsa_gitlab
```

This is my repo.yaml record:

```yaml
odoo_web_login:
  defaults:
    depth: $DEPTH_MERGE
  remotes:
    origin: ssh://realsystems.ddns.net/carlosecv/odoo_web_login.git
  target: origin $ODOO_VERSION
  merges:
    - origin $ODOO_VERSION
```

It seems that my config file is not taken into account.

If i use `git clone ssh://realsystems.ddns.net/emueble/espacio-mueble-customizations.git`
on my computer outside containers im getting ok.

What i have missed?, Thanks

**Comment by Yajo** [comment]
Have you created `odoo/custom/ssh/id_rsa_gitlab` and `odoo/custom/ssh/id_rsa_gitlab.pub` files?

**Comment by carlosecv** [comment]
Yes I did
Do I have to do something more ?

Maybe the path is not correct /opt/odoo/custom/ssh/ ?

**Comment by carlosecv** [comment]
I did it 
You must add previously on known_hosts file 
ssh-keyscan realsystems.ddns.net

then it worked
