### ISSUE TITLE
PDF Reports it wont shows up correctly

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#53]
Hello I tried several Odoo versions from copier but none of them are renering PDF Company Logo correctly:

Logo on Company defined:

![image](https://user-images.githubusercontent.com/7633676/82127897-756c6b80-977c-11ea-9467-e7db4517d72a.png)

Sale Order Printed:
![image](https://user-images.githubusercontent.com/7633676/82127827-21fa1d80-977c-11ea-9eb8-9f614745b623.png)

Do you think I have missed something?

**Comment by theangryangel** [comment]
Add the system parameter `report.url` and set it to `http://localhost:8069`

This will force Odoo and wkhtmltopdf to use that url rather than web.base.url which is probably being set to localhost:xx069, which isn’t accessible inside the container.

**Comment by pedrobaeza** [comment]
Yes, that's it! Thanks for answering, @theangryangel

**Comment by carlosecv** [comment]
Thank you it works!!

On Odoo database:
Configuration->Technical->Parameters->System Parameters

Add 
report.url 
value: http://localhost:8069/
