### ISSUE TITLE
Trying productive environment fail

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#55]
Hi

I did all the steps to get up odoo v11 with copier and succecsfuly got my http://localhost:11069 environment running

Now I tried to make it run on a productive way, so i got stuck with this error:

WARNING: The SMTP_REAL_NON_CANONICAL_DEFAULT variable is not set. Defaulting to a blank string.
ERROR: Network "dmoemuebles2_default" needs to be recreated - option "encrypted" has changed

Steps:

I created my copier instance:

 copier copy gh:Tecnativa/doodba-copier-template dmoemuebles2

I linked my tests domains to this server and so i give to copier this basic answers:

# Changes here will be overwritten by Copier
_commit: v1.5.4
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: true
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_tz: UTC
cidr_whitelist: null
domain_prod: dmoemuebles2.realsystems.com.mx
domain_prod_alternatives: www.realsystems.com.mx
domain_test: dmoemuebles3.realsystems.com.mx
gitlab_url: null
odoo_dbfilter: .*
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 11.0
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: 11
project_author: RS
project_license: AGPL-3.0-or-later
project_name: dmoemuebles
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null

I creates on a separate directory my traefik global proxy:

inverseproxy.yaml

version: "2.1"
services:
  proxy:
    image: traefik:1.6-alpine
    networks:
      shared:
      private:
      public:
    volumes:
      - acme:/etc/traefik/acme:rw,Z
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockersocket
    restart: unless-stopped
    privileged: true
    tty: true
    command:
      - --ACME.ACMELogging
      - --ACME.Email=you@example.com
      - --ACME.EntryPoint=https
      - --ACME.HTTPChallenge.entryPoint=http
      - --ACME.OnHostRule
      - --ACME.Storage=/etc/traefik/acme/acme.json
      - --DefaultEntryPoints=http,https
      - --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --EntryPoints=Name:https Address::443 TLS
      - --LogLevel=INFO
      - --Docker
      - --Docker.EndPoint=http://dockersocket:2375
      - --Docker.ExposedByDefault=false
      - --Docker.Watch
  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped
networks:
  shared:
    internal: true
    driver_opts:
      encrypted: 1
  private:
    internal: true
    driver_opts:
      encrypted: 1
  public:
volumes:
  acme:

so i run:

docker-compose -p inverseproxy -f inverseproxy.yaml up -d

Now my web page says:

![image](https://user-images.githubusercontent.com/7633676/83334220-8f24ad00-a26a-11ea-95a5-39cec2a8eb88.png)

So I modified my .dockers files:
vi .docker/db-access.env 
vi .docker/db-creation.env 
vi .docker/odoo.env 
vi .docker/smtp.env

And make it to match test environment values and:

docker-compose -f prod.yaml up -d

I got this error:
WARNING: The SMTP_REAL_NON_CANONICAL_DEFAULT variable is not set. Defaulting to a blank string.
ERROR: Network "dmoemuebles2_default" needs to be recreated - option "encrypted" has changed

Now I tried
docker-compose down
docker-compose -f prod.yaml up -d
docker-compose up

And got nothin different now Im stuck did you see some insight what do i missed?

Thanks

**Comment by pedrobaeza** [comment]
docker-compose build --pull
docker-compose down
docker-compose up -d

**Comment by carlosecv** [comment]
Excelent thank you very much Pedro

I hope you can give me some insight on this I think its not an issue from copier.

![image](https://user-images.githubusercontent.com/7633676/83339207-15ec8080-a291-11ea-8ccc-0799bf59d429.png)

**Comment by pedrobaeza** [comment]
Probably you haven't deploy the general proxy in your server, but without more information is difficult to say.

**Comment by carlosecv** [comment]
Pedro I create on a separate directory my traefik global proxy:

inverseproxy.yaml

version: "2.1"
services:
proxy:
image: traefik:1.6-alpine
networks:
shared:
private:
public:
volumes:
- acme:/etc/traefik/acme:rw,Z
ports:
- "80:80"
- "443:443"
depends_on:
- dockersocket
restart: unless-stopped
privileged: true
tty: true
command:
- --ACME.ACMELogging
- --ACME.Email=you@example.com
- --ACME.EntryPoint=https
- --ACME.HTTPChallenge.entryPoint=http
- --ACME.OnHostRule
- --ACME.Storage=/etc/traefik/acme/acme.json
- --DefaultEntryPoints=http,https
- --EntryPoints=Name:http Address::80 Redirect.EntryPoint:https
- --EntryPoints=Name:https Address::443 TLS
- --LogLevel=INFO
- --Docker
- --Docker.EndPoint=http://dockersocket:2375
- --Docker.ExposedByDefault=false
- --Docker.Watch
dockersocket:
image: tecnativa/docker-socket-proxy
privileged: true
networks:
private:
volumes:
- /var/run/docker.sock:/var/run/docker.sock
environment:
CONTAINERS: 1
NETWORKS: 1
SERVICES: 1
SWARM: 1
TASKS: 1
restart: unless-stopped
networks:
shared:
internal: true
driver_opts:
encrypted: 1
private:
internal: true
driver_opts:
encrypted: 1
public:
volumes:
acme:

so i run:

docker-compose -p inverseproxy -f inverseproxy.yaml up -d

Is this ok?

**Comment by pedrobaeza** [comment]
I can't say about that. Maybe @Yajo can answer.

**Comment by carlosecv** [comment]
Thank you Pedro

I know I still have to learn more to get this done

**Comment by carlosecv** [comment]
Indeed I have this configuration with traefik:

![image](https://user-images.githubusercontent.com/7633676/83432118-02aaf380-a3fe-11ea-886b-cd7bcf0dfe7d.png)

How can i put prod.yaml in tune with this to allow dmoemueble2.realsystems.com.mx to link to odoo container?

my prod.yaml file:

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "$INITIAL_LANG"
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      traefik.longpolling.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/longpolling/"
      traefik.www.frontend.rule: "Host:${DOMAIN_PROD}"
      traefik.forbid-crawlers.frontend.rule: "Host:${DOMAIN_PROD};PathPrefix:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}"
      # Main service
      traefik.http.middlewares.dmoemueble2-11-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.dmoemueble2-11-0-prod-compress.compress: "true"
      traefik.http.routers.dmoemueble2-11-0-prod-main.entrypoints: "web-main"
      traefik.http.routers.dmoemueble2-11-0-prod-main.middlewares:
        dmoemueble2-11-0-prod-buffering,
        dmoemueble2-11-0-prod-compress
      traefik.http.routers.dmoemueble2-11-0-prod-main.rule: "host(`${DOMAIN_PROD}`)"
      traefik.http.routers.dmoemueble2-11-0-prod-main.service: "dmoemueble2-11-0-prod-main"
      traefik.http.routers.dmoemueble2-11-0-prod-main.tls: "true"
      traefik.http.routers.dmoemueble2-11-0-prod-main.tls.certresolver: "letsencrypt"
      traefik.http.services.dmoemueble2-11-0-prod-main.loadbalancer.server.port: 8069
      # Longpolling service
      traefik.http.routers.dmoemueble2-11-0-prod-longpolling.entrypoints: "web-main"
      traefik.http.routers.dmoemueble2-11-0-prod-longpolling.rule:
        "host(`${DOMAIN_PROD}`) && pathprefix(`/longpolling/`)"
      traefik.http.routers.dmoemueble2-11-0-prod-longpolling.service: "dmoemueble2-11-0-prod-longpolling"
      traefik.http.services.dmoemueble2-11-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.dmoemueble2-11-0-prod-longpolling.tls: "true"
      traefik.http.routers.dmoemueble2-11-0-prod-longpolling.tls.certresolver: "letsencrypt"
      # Forbid crawlers
      ? traefik.http.middlewares.dmoemueble2-11-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag
      : "noindex, nofollow"
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.entrypoints: "web-main"
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.middlewares:
        dmoemueble2-11-0-prod-buffering,
        dmoemueble2-11-0-prod-compress,
        dmoemueble2-11-0-prod-forbid-crawlers
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.rule:
        Host(`${DOMAIN_PROD}`) && Path(`/web`, `/web/{anything:.*}`, `/website/info`, `/website/info/{anything:.*}`)
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.service: "dmoemueble2-11-0-prod-main"
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.tls: "true"
      traefik.http.routers.dmoemueble2-11-0-prod-forbidden-crawlers.tls.certresolver: "letsencrypt"

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:

**Comment by Yajo** [comment]
Hi there!

Thanks for taking the time to report the problem, but **it seems like this is not exactly a bug** in this project's code and/or scope. It is more likely a problem on your specific deployment, instance or configuration.

Doodba is a project that sews many others together, such as:

- [click-odoo-contrib](https://github.com/acsone/click-odoo-contrib)
- [Copier](https://github.com/pykong/copier)
- [Docker Compose](https://docs.docker.com/compose/)
- [Docker](https://www.docker.com/)
- [Git Aggregator](https://github.com/acsone/git-aggregator)
- [Git](https://git-scm.com/)
- [Gitlab](https://gitlab.com/)
- [OCA](https://odoo-community.org/)
- [Odoo](https://www.odoo.com/)
- [Traefik](https://traefik.io)

When you use Doodba, you are expected to know those tools. Although this project includes some documentation that is specific for some of those components, we don't aim to replace their own documentation or support channels, which might be documentation, a mailing list, a chat room, a help forum, commercial support, etc.


It seems your problem is more related to Traefik.

I hope you can get proper help there. If you find out that your problem was finally caused by Doodba itself or that some if our docs are missing, incomplete, outdated or confusing, please feel free to reopen this issue, open a new one, or even contribute a PR to improve the situation.

To keep the bug tracker clean and focused, This issue will stay closed. I hope you understand and don't take that personally. 😊

Have a nice day!

**Comment by carlosecv** [comment]
Thank you very much Yaho to take the time to answer me.

I know this is not the forum to learn other technologies =)

Your tips are very welcome and very usefull.

"To keep the bug tracker clean and focused, This issue will stay closed. I hope you understand and don't take that personally. ￼"

Never Yaho, this is an Open Source Project and I apreciate you and Pedro take the time to answer us as your possibilities.

I will try to contribute to this project on my possibilities with my discoveries in the way of a newbie.

Regards.
