### ISSUE TITLE
Generated files don't pass pre-commit hook?

### ISSUE THREAD

**Issue by joshuashort** [Tecnativa/doodba-copier-template#66]
First of all, this project is awesome! I wish this was around a few years ago :)

Maybe I've got something set up wrong, but getting started and some pretty basic usage seems to have some rough edges:

1. After running`copier copy gh:Tecnativa/doodba-copier-template doodba-test`, trying to commit the resulting repo seems fails pre-commit linting on these files:
    * `.copier-answers.yml`
    * `prod.yaml`
    * `test.yaml`

2. The same seem to happen on `copier --force update`

**Comment by Yajo** [comment]
Your question is a good one for the FAQ. Fix (answer) in #67.

> First of all, this project is awesome! I wish this was around a few years ago :)

Thanks! It would have existed before [if Copier or any decent alternative existed before](https://www.recallstack.icu/en/2020/04/18/yeoman-and-cookiecutter-are-dead-long-live-copier/) :stuck_out_tongue_closed_eyes:
