### ISSUE TITLE
how project's `odoo/custom/ssh` is supposed to propogate inside the container if ssh folder is not mounted as a volume in setup-devel.yaml?

### ISSUE THREAD

**Issue by iledarn** [Tecnativa/doodba-copier-template#80]
https://github.com/Tecnativa/doodba-copier-template/blob/9a33b2e3adf4f98b2f93f02ee99189271f8a5461/setup-devel.yaml.jinja#L32

**Comment by iledarn** [comment]
Steps to reproduce:
 invoke git-aggregate

Current behavior:
 key_load_public: invalid format
 Host key verification failed.
 fatal: Could not read from remote repository.

 inside the container root's .ssh folder contains empty id_rsa

desired behavior:
 to use odoo/custom/ssh when dealing with private repositories

**Comment by iledarn** [comment]
This https://github.com/Tecnativa/doodba-copier-template/pull/81 fixes it, but there is another problem occurs when `invoke git-aggregate`: `Bad owner or permissions on /root/.ssh/config`. I only know the workaround for it - `chown root:root config` - don't sure this is a proper way

**Comment by iledarn** [comment]
I've found out that there is
::
 ONBUILD RUN mkdir -p /opt/odoo/custom/ssh \                                                                                                                                                                                                                                      
            && ln -s /opt/odoo/custom/ssh ~root/.ssh \                                                                                                                                                                                                                           
            && chmod -R u=rwX,go= /opt/odoo/custom/ssh \                                                                                                                                                                                                                         
            && sync

so I should put my keys into `odoo/custom/ssh` before build, right?

**Comment by iledarn** [comment]
or if I change the content of my odoo/custom/ssh folder - I should rebuild the image

**Comment by iledarn** [comment]
ONBUILD COPY $LOCAL_CUSTOM_DIR /opt/odoo/custom

**Comment by iledarn** [comment]
`ONBUILD RUN mkdir -p /opt/odoo/custom/ssh \`

It seems that this mkdir doesn't create anything because the dir is already there - we copy all $LOCAL_CUSTOM with ssh in it

**Comment by theangryangel** [comment]
For ssh keys and configs added after the initial build I do a force build that prevents it from using the cache. It does not pick up that the files have changed, I’ve never bothered investigating further as it’s a very uncommon event for us.

**Comment by Yajo** [comment]
> or if I change the content of my odoo/custom/ssh folder - I should rebuild the image

Indeed, that's the fix you're looking for, and the reason is explained by @theangryangel: it's very uncommon. Closing.
