### ISSUE TITLE
Question: Web Control Panel

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#87]
¿Is there a Web Control Panel or something like this to manage copier instances?

Some planning project to do or you see this as an unusefull feature?

**Comment by theangryangel** [comment]
If you’re looking to manage docker containers via a GUI, then portainer is probably your best bet (if you’re on a single docker host or a swarm).

**Comment by carlosecv** [comment]
Thank you theangryangel I will checkit out.

I mean something related with copier like a copier instances administrator.

**Comment by Yajo** [comment]
Sorry I don't understand the question. What is for you a "copier instance"?

**Comment by carlosecv** [comment]
> Sorry I don't understand the question. What is for you a "copier instance"?

Imagine a web panel where do you can record  the answers that asked by copier and put the modules that are required by repo.yaml and addons.yaml, then , trought this panel we create that "instance" on a server with docker.

Then we can have a database with instances related to customers, versions of systems on this panel and keep a control of this matters.

Regards.

**Comment by Yajo** [comment]
Sorry but Copier is not a tool for infrastructure management. It can be used by those tools, of course.

Take a glance at Ansible, Ansible Tower and Portainer. They might be more similar to what you're looking for.

**Comment by carlosecv** [comment]
Thank you Yaho I will
