### ISSUE TITLE
Issue computed fields based on other computed fields stop working some cases

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#89]
Odoo v11

I have sale_margin and sale_management modules so 

I  inherit sale_order on new model sale_option
Created new views for this new model
If I try to get computed margin on new model sale_option it doesnt work.

¿Something about memory maybe?

This sale_option module works on a linux server without docker copier versions 

If we try on copier docker version (devel or prod ambients) I have bad results on computed fields or on_change methods they simply stop working on some cases.

Case Samples:

Inherith product_template and add some on_change method depending on other fields

If you open product_template normal form (Maybe Sales->Master Data -> Product) it works, but if you try to create a product from a Many2One selector and open the form from this point, this on_change methods stop working.

**Comment by pedrobaeza** [comment]
Sorry, but this has nothing to do with Doodba itself. You should look for other things.

**Comment by carlosecv** [comment]
Do you think  maybe memory cached values are affected in some way by this configuration?

Its has not happened to some one else?

**Comment by carlosecv** [comment]
I see other issues like this on proffessional_templates module where calculates num2words on multiple anidated functions that doesnt work inside copier instance but it works outside dockerized ambient.

On this kind of operations failed:

  words=num2words(self.amount_total,lang=self.partner_id.lang)
                currency=self.currency_id.currency_name or ''
                amount_words=words + ' ' + currency
                self.amount_words = amount_words.upper()

I have to change this algorithm to get it work so, maybe something on this doodba image need to be tunned ¿what you think?

**Comment by carlosecv** [comment]
You where right from mi original Issue it was a problem with methods that access to different objects.

I will check inside other issues like this before to see problems on doodba thank you Manuel.
