### ISSUE TITLE
odoo: error: no such option: --limit-time-real-cron

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#91]
For copier odoo v8
Standard answers

odoo_1                    | Usage: odoo [options]
odoo_1                    | 
odoo_1                    | odoo: error: no such option: --limit-time-real-cron
odoo_1                    | doodba INFO: Waiting until postgres is listening at db...
odoo_1                    | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1                    | doodba INFO: File /opt/odoo/auto/odoo.conf exists, skipping config generation
odoo_1                    | doodba INFO: Executing odoo --limit-memory-soft=0 --limit-time-real-cron=9999999 --limit-time-real=9999999 --workers=0
odoo_1                    | Usage: odoo [options]
odoo_1                    | 
odoo_1                    | odoo: error: no such option: --limit-time-real-cron

**Comment by carlosecv** [comment]
editing devel.yaml

    command:
      - odoo
      - --limit-memory-soft=0
      - --limit-time-real-cron=9999999
      - --limit-time-real=9999999
      - --workers=0

Removing lines:
      - --limit-memory-soft=0
      - --limit-time-real-cron=9999999
      - --limit-time-real=9999999

Doit ok.

**Comment by carlosecv** [comment]
I confirm this happens too for openerp 7

**Comment by Yajo** [comment]
Yes, the issue was fixed but the new template version isn't still released because there are other pending changes.

**Comment by carlosecv** [comment]
Thank you!
