### ISSUE TITLE
Question: Automatic responses to copier

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#95]
Hello

copier --answers-file my_answers ~/project_path

¿some syntax sample of my_answers file?

I tried .copier-answers.yml but every time I do:

copier -a my_answers

ask again all questions, ¿where do i put the AWS_S3 Key for example or other passwords like odoo admin password on this file?

Thank you

**Comment by Yajo** [comment]
Copier questions are to be asked in the copier community: https://github.com/copier-org/copier

**Comment by carlosecv** [comment]
Sorry
