### ISSUE TITLE
Documentation daily usage says pgweb

### ISSUE THREAD

**Issue by carlosecv** [Tecnativa/doodba-copier-template#97]
Documentation daily usage says about gweb

But I cant see how to run it

**Comment by pedrobaeza** [comment]
Please don't use issues as question tracker. It's clearly put in its section though: https://github.com/Tecnativa/doodba-copier-template/blob/master/docs/daily-usage.md#pgweb

**Comment by carlosecv** [comment]
Im sorry but it didnt say how to run it just say it came with development

**Comment by pedrobaeza** [comment]
![Selección_015](https://user-images.githubusercontent.com/7165771/90992190-4f8e0880-e5ae-11ea-97ea-764c4d8b2687.png)

**Comment by pedrobaeza** [comment]
Start your Doodba, of course.

**Comment by carlosecv** [comment]
I did it but doesnt response, i think it will be like wdb but it didnt work the same

**Comment by Yajo** [comment]
You're reviewing docs for master, where the feature exists. But it hasn't still been released. Please read docs for the specific version of the template you're using.

**Comment by carlosecv** [comment]
Thank you Yajo I will
